gui:
  score: 
    status: true
  textBox:
    status: false
    title: "Chord"
  pianoRoll:
    status: true
    human: true
    agent: true
  keyboard:
    status: true
    octaveStart: 2
    octaveEnd: 6
  chromaChart:
    status: true
  audioMeter: 
    status: true
  monitor:
    status: true
    title: "Monitor"
    structure:
      - label: "Agent"
        parameters:
          - id: 3
            label: "Inference"
            interval: 100 
            graph: true
            min: 80
            max: 130
      - label: "Audio"
        parameters:
          # The 'id' for each parameter must be unique and is used
          # in the hooks for adding new values for monitoring
          # The 'label' is the parameter name that appears in the GUI.
          # The 'interval' is the refresh rate of the parameter in ms.
          # The 'graph' flag allows you to visualize the value as a time grpah.
          # The 'min' and 'max' indicate the expected range of the parameter.
          - id: 0 
            label: "rms" 
            interval: 10
            graph: true
            min: 0
            max: 0.5
  settingsModal:
    sliders:
      - id: 1
        label: "Randomness"
        value: 0
        min: 0
        max: 10
      - id : 2
        label: "Delay"
        value: 8
        min : 1
        max : 16
      - id : 3
        label: "Pitch Shift"
        value: 0
        min: 0
        max: 24